# Generated by Django 3.1.7 on 2021-04-02 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tm33t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(auto_now=True, verbose_name='tm33t time')),
                ('content', models.TextField()),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm33ts', to=settings.AUTH_USER_MODEL)),
                ('users_liked', models.ManyToManyField(related_name='tm33ts_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
