# Generated by Django 3.1.7 on 2021-03-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmitt3r', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tm33t',
            name='posted_time',
        ),
        migrations.AddField(
            model_name='tm33t',
            name='post_time',
            field=models.DateTimeField(auto_now=True, verbose_name='tm33t time'),
        ),
    ]
