# Generated by Django 3.1.7 on 2021-04-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmitt3r', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('tm33t_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tmitt3r.tm33t')),
                ('related_tm33t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tmitt3r.tm33t')),
            ],
            bases=('tmitt3r.tm33t',),
        ),
    ]
