# Generated by Django 3.1.7 on 2021-04-11 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmitt3r', '0002_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retm33t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_retm33ted', models.DateTimeField(auto_now=True)),
                ('related_tm33t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmitt3r.tm33t')),
                ('user_retm33ted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tm33t',
            name='users_retm33ted',
            field=models.ManyToManyField(through='tmitt3r.Retm33t', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='retm33t',
            constraint=models.UniqueConstraint(fields=('user_retm33ted', 'related_tm33t'), name='unique_retm33t'),
        ),
    ]
