# Generated by Django 3.1.7 on 2021-04-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmitt3r', '0002_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tm33t',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
