# Generated by Django 3.1.7 on 2021-04-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmitt3r', '0003_auto_20210412_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retm33t',
            fields=[
                ('tm33t_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tmitt3r.tm33t')),
                ('tm33t_retm33ted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retm33ts', to='tmitt3r.tm33t')),
            ],
            bases=('tmitt3r.tm33t',),
        ),
    ]
