# Generated by Django 3.1.7 on 2021-03-21 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmitt3r', '0003_followrelationship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowRelationship',
            new_name='Follows',
        ),
        migrations.AddConstraint(
            model_name='follows',
            constraint=models.UniqueConstraint(fields=('actor', 'followed_user'), name='unique_follow'),
        ),
    ]
