# Generated by Django 3.1.7 on 2021-03-25 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmitt3r', '0005_delete_follows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_actor', to=settings.AUTH_USER_MODEL)),
                ('liked_tm33t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_liked_tm33t', to='tmitt3r.tm33t')),
            ],
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('actor', 'liked_tm33t'), name='unique_like'),
        ),
    ]
