# Generated by Django 3.1.7 on 2021-03-26 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmitt3r', '0006_auto_20210325_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
